apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-frontend
  template:
    metadata:
      labels:
        app: bank-frontend
    spec:
      containers:
        - name: bank-frontend
          image: quay.io/mmartofe/bank-frontend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: bank-frontend
spec:
  selector:
    app: bank-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bank-frontend
spec:
  to:
    kind: Service
    name: bank-frontend
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
