resources:
# Postgres
- configmap-postgres.yaml
- deployment.yaml
- service.yaml
# Backend
- configmap-backend.yaml
- deployment.yaml
- service.yaml
# Frontend
- configmap-frontend.yaml
- deployment.yaml
- service.yaml
- route.yaml