apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: 'postges'
    app.openshift.io/vcs-uri: 'https://github.com/mmartofel/kuberneter-backend.git'
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/part-of: BANK_ACCOUNT_MANAGEMENT
    app.openshift.io/runtime: quarkus
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: backend
  template:
    metadata:
     labels:
      deployment: backend
    spec:
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: configmap-backend
        startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        image: quay.io/mmartofe/bank-account-management-backend:main
        imagePullPolicy: ifNotPresent
        name: backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
