apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
spec:
  ports:
  - name: http-8080
    port: 8080
    targetPort: 8080
  - name: https-8443
    port: 8443
    targetPort: 8443
  - name: https-8778
    port: 8778
    targetPort: 8778
  selector:
    deployment: backend
  type: ClusterIP
  sessionAffinity: None    